# Generated by Django 4.2.16 on 2024-09-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='email',
        ),
    ]
